elasticsearch:
  host: localhost
  port: 9200
  elasticTypes:
    defaultText: '{"type": "text", "fields": { "keyword": { "type": "keyword", "ignore_above": 256}}}'
    defaultKeyword: '{"type" : "keyword"}'
    defaultDate: '{"type" : "date"}'
    defaultBoolean: '{"type" : "boolean"}'
    defaultLong: '{"type" : "long"}'
  typeMappings:
    Text: ${elasticsearch.elasticTypes.defaultText}
    Date: ${elasticsearch.elasticTypes.defaultDate}
    YesOrNo: ${elasticsearch.elasticTypes.defaultBoolean}
    Email: ${elasticsearch.elasticTypes.defaultKeyword}
    FixedList : ${elasticsearch.elasticTypes.defaultText}
    MultiSelectList : ${elasticsearch.elasticTypes.defaultText}
  indexCasesNameFormat: "%s_%s_cases"
  indexCasesType: case
  caseMappings:
    reference: ${elasticsearch.elasticTypes.defaultKeyword}
    jurisdiction: ${elasticsearch.elasticTypes.defaultText}
    id: ${elasticsearch.elasticTypes.defaultLong}
    state: ${elasticsearch.elasticTypes.defaultKeyword}
    created_date: ${elasticsearch.elasticTypes.defaultDate}
    last_modified: ${elasticsearch.elasticTypes.defaultDate}
    security_classification: ${elasticsearch.elasticTypes.defaultKeyword}
    case_type_id: ${elasticsearch.elasticTypes.defaultKeyword}




