elasticsearch:
  host: localhost
  port: 9200
  elasticTypes:
    defaultText: '{"type": "text", "fields": { "keyword": { "type": "keyword", "ignore_above": 256}}}'
    defaultKeyword: '{"type" : "keyword"}'
    defaultDate: '{"type" : "date"}'
    defaultBoolean: '{"type" : "boolean"}'
    defaultLong: '{"type" : "long"}'
    defaultDouble: '{"type" : "double"}'
  typeMappingsIgnored:
    - Label
  typeMappings:
    Text: ${elasticsearch.elasticTypes.defaultText}
    TextArea: ${elasticsearch.elasticTypes.defaultText}
    Number: ${elasticsearch.elasticTypes.defaultDouble}
    Date: ${elasticsearch.elasticTypes.defaultDate}
    Time: ${elasticsearch.elasticTypes.defaultDate}
    DateTime: ${elasticsearch.elasticTypes.defaultDate}
    PhoneUK: ${elasticsearch.elasticTypes.defaultKeyword}
    MoneyGBP: ${elasticsearch.elasticTypes.defaultDouble}
    YesOrNo: ${elasticsearch.elasticTypes.defaultBoolean}
    Email: ${elasticsearch.elasticTypes.defaultKeyword}
    Postcode: ${elasticsearch.elasticTypes.defaultKeyword}
    Document: ${elasticsearch.elasticTypes.defaultKeyword}
    FixedList : ${elasticsearch.elasticTypes.defaultText}
    FixedListEdit : ${elasticsearch.elasticTypes.defaultText}
    MultiSelectList : ${elasticsearch.elasticTypes.defaultText}
  indexCasesNameFormat: "%s_%s_cases"
  indexCasesType: case
  caseMappings:
    reference: ${elasticsearch.elasticTypes.defaultKeyword}
    jurisdiction: ${elasticsearch.elasticTypes.defaultText}
    id: ${elasticsearch.elasticTypes.defaultLong}
    state: ${elasticsearch.elasticTypes.defaultKeyword}
    created_date: ${elasticsearch.elasticTypes.defaultDate}
    last_modified: ${elasticsearch.elasticTypes.defaultDate}
    security_classification: ${elasticsearch.elasticTypes.defaultKeyword}
    case_type_id: ${elasticsearch.elasticTypes.defaultKeyword}




