elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  enabled: true
  indexShards: 2
  indexShardsReplicas: 3
  elasticMappings:
    disabled: '{"enabled": false}'
    defaultText: '{"type": "text", "fields": { "keyword": { "type": "keyword", "ignore_above": 256}}}'
    defaultKeyword: '{"type" : "keyword"}'
    defaultDate: '{"type" : "date"}'
    defaultBoolean: '{"type" : "boolean"}'
    defaultLong: '{"type" : "long"}'
    defaultDouble: '{"type" : "double"}'
  ccdIgnoredTypes:
    - Label
    - CasePaymentHistoryViewer
  typeMappings:
    Text: ${elasticsearch.elasticMappings.defaultText}
    TextArea: ${elasticsearch.elasticMappings.defaultText}
    Number: ${elasticsearch.elasticMappings.defaultDouble}
    Date: ${elasticsearch.elasticMappings.defaultDate}
    Time: ${elasticsearch.elasticMappings.defaultDate}
    DateTime: ${elasticsearch.elasticMappings.defaultDate}
    PhoneUK: ${elasticsearch.elasticMappings.defaultKeyword}
    MoneyGBP: ${elasticsearch.elasticMappings.defaultDouble}
    YesOrNo: ${elasticsearch.elasticMappings.defaultBoolean}
    Email: ${elasticsearch.elasticMappings.defaultKeyword}
    Postcode: ${elasticsearch.elasticMappings.defaultKeyword}
    Document: ${elasticsearch.elasticMappings.defaultKeyword}
    FixedList: ${elasticsearch.elasticMappings.defaultText}
    FixedListEdit: ${elasticsearch.elasticMappings.defaultText}
    MultiSelectList: ${elasticsearch.elasticMappings.defaultText}
  indexCasesNameFormat: "%s_%s_cases"
  indexCasesType: case
  casePredefinedMappings:
    reference: ${elasticsearch.elasticMappings.defaultKeyword}
    jurisdiction: ${elasticsearch.elasticMappings.defaultText}
    id: ${elasticsearch.elasticMappings.defaultLong}
    state: ${elasticsearch.elasticMappings.defaultKeyword}
    created_date: ${elasticsearch.elasticMappings.defaultDate}
    last_modified: ${elasticsearch.elasticMappings.defaultDate}
    security_classification: ${elasticsearch.elasticMappings.defaultKeyword}
    case_type_id: ${elasticsearch.elasticMappings.defaultKeyword}
    '@timestamp': ${elasticsearch.elasticMappings.disabled}
    '@version': ${elasticsearch.elasticMappings.disabled}




